<a href="https://colab.research.google.com/github/archika08/Blockchain-certificates/blob/master/Copy_of_data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt       #here pyplot is the module of the matplotlib library
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('Data.csv')
X= dataset.iloc[:, :-1].values   #features are called dependent variables(first few columns) and the column we are trying to predict is the dependent variable(usually last column)
#-1 represnets the last column iloc[rows,columns]
#rows- : means all rows
#columns- :-1 all columns except the last one
y=dataset.iloc[:,-1].values


In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')  #creating new object(instance)
imputer.fit(X[:,1:3])      #only on numerical columns
X[:,1:3]=imputer.transform(X[:,1:3])

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers= [('encoder',OneHotEncoder(),[0])],remainder='passthrough') 
#Each transformer is a three-element tuple that defines the name of the transformer, the transform to apply, and the column indices to apply it to. For example: (Name, Object, Columns)
#Setting remainder=’passthrough’ will mean that all columns not specified in the list of “transformers” will be passed through without transformation, instead of being dropped.
X= np.array(ct.fit_transform(X)) #fit_transform doesnt give the final output as an nd array

In [ ]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)



In [ ]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


## Feature Scaling

In [ ]:
#always apply feature scaling after splitting dataset into training and test set to prevent infromation leakage
#standardisation makes value range betweem -3 to 3 and normalisation makes value range between 0 to 1
#never apply standardisation on dummy variables which we got after doing one-hot encoding as (1)they are already b/w -3 to 3 (2)it gives nonsensical numerical values that would lead to lose the interpretaion of these variables (of which country corresponds to which combination of 0 and 1)
#apply it to only numerical values
from sklearn.preprocessing import StandardScaler
Sc=StandardScaler()
X_train[:,3:]=Sc.fit_transform(X_train[:,3:])
X_test[:,3:]=Sc.transform(X_test[:,3:])

In [ ]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578368 -1.0781259408428199]
 [0.0 1.0 0.0 -0.014117293757060787 -0.07013167641153722]
 [1.0 0.0 0.0 0.5667085065333244 0.6335624327124908]
 [0.0 0.0 1.0 -0.3045301939022441 -0.3078661727424107]
 [0.0 0.0 1.0 -1.9018011447008007 -1.4204636155518073]
 [1.0 0.0 0.0 1.1475343068236983 1.232653363458408]
 [0.0 1.0 0.0 1.4379472069689012 1.574991038157016]
 [1.0 0.0 0.0 -0.7401495441200345 -0.5646194287793399]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [ ]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578276 -1.0781259408428199]
 [0.0 1.0 0.0 -0.014117293757059871 -0.07013167641153731]
 [1.0 0.0 0.0 0.5667085065333253 0.6335624327124907]
 [0.0 0.0 1.0 -0.3045301939022432 -0.3078661727424108]
 [0.0 0.0 1.0 -1.9018011447007999 -1.4204636155518073]
 [1.0 0.0 0.0 1.1475343068236992 1.232653363458408]
 [0.0 1.0 0.0 1.437947206968902 1.574991038157016]
 [1.0 0.0 0.0 -0.7401495441200336 -0.56461942877934]]
